###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL
##############################################################################################################
# конфигурация подключения к серверу MSSQL
mssql_dataserver: "user-pc1\\wincc"  # сервер на котором база данных # \\ тут не спроста, именно двойной!!!
mssql_db: "MESDB"                    # имя базы данных
mssql_user: "sa"                     # логин
mssql_pass: "13245768"               # пароль
mssql_port: 1433                     # порт сервера
mssql_azure: false                   # Azure? True или False?

# конфигурация работы с таблицой
mssql_table1: "dbo.Movements"        # таблица к которой обращаемся
mssql_limit: "TOP 3"                 # ограничиваем количество возвращаемых строк
mssql_what: "*"                      # какие столбцы запрашиваем
mssql_where: ""                      # фильтруем по условию
mssql_group: ""                      # группируем ли?
mssql_order: ""                      # сортируем ли?
##############################################################################################################
###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL###MSSQL

###POSTGRESQL###POSTGRESQL###POSTGRESQL###POSTGRESQL###POSTGRESQL###POSTGRESQL###POSTGRESQL###POSTGRESQL###POSTGRESQL###POSTGRESQL
################################################################################################################################
# конфигурация подключения к серверу MSSQL
pg_host: "localhost"                 # сервер на котором база данных # \\ тут не спроста, именно двойной!!!
pg_db: "postgres"                    # имя базы данных
pg_user: "postgres"                  # логин
pg_pass: "13245768"                  # пароль
pg_port: 5432                        # порт сервера
pg_options: ""                       # дополнительные параметры соединения
pg_tty: ""                           # отладочный терминал TTY (не использую)

# конфигурация работы с таблицой
pg_table1: "public.wincc_movements"        # таблица к которой обращаемся
pg_limit: "TOP 3"                # ограничиваем количество возвращаемых строк
pg_what: "*"                      # какие столбцы запрашиваем
pg_where: ""                      # фильтруем по условию
pg_group: ""                      # группируем ли?
pg_order: ""                      # сортируем ли?
################################################################################################################################
###POSTGRESQL###POSTGRESQL###POSTGRESQL###POSTGRESQL###POSTGRESQL###POSTGRESQL###POSTGRESQL###POSTGRESQL###POSTGRESQL###POSTGRESQL
